version: '2'
services:
  qedu-provas-front:
    container_name: qedu-provas-front
    image: "qedu/qedu-provas-base-front-infra:release-1.1.0"
    working_dir: /var/www/qedu-provas-front
    restart: always
    command: bash -c "yarn && yarn start:dev"
    volumes:
      - ../:/var/www/qedu-provas-front
    environment:
      - TERM=xterm-256color
    networks:
      - qedu-provas-front-tier

  qedu-provas-nginx:
    container_name: qedu-provas-nginx
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "4200:4200"
    links:
      - qedu-provas-front
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/logs/:/var/log/nginx
    networks:
      - qedu-provas-front-tier

networks:  
  qedu-provas-front-tier:
    driver: bridge