version: '3'

services:

  provas:
    image: qedu_provas_front
    container_name: qedu_provas_front
    restart: always
    command: ["yarn", "start:dev"]
    ports:
      - "80:4200"
      - "4200:4200"
    volumes:
      - ../:/var/www/qedu-provas-front
